credentials:
  usernames:
    kartikkwatra:
      email: kartik@howindialives.com
      failed_login_attempts: 0 # Will be managed automatically
      # logged_in: False # Will be managed automatically
      name: Kartik Kwatra
      password: egging kept raider wrench # Will be hashed automatically
cookie:
  expiry_days: 1
  key: unknotted unable tumble bunt # Must be string
  name: auth